from dataclasses import dataclass
from enum import Enum
import pandas as pd 

class EventType(str, Enum):
    MARKET = 'MARKET'
    SIGNAL = 'SIGNAL'
    ORDER = 'ORDER'
    FILL = 'FILL'

class Event:
    #base class for all events
    type: EventType


@dataclass
class MarketEvent(Event):
    #indicates new market data is available
    type: EventType = EventType.MARKET

@dataclass
class SignalEvent(Event):
    #generated by a strategy
    symbol: str
    datetime: pd.Timestamp
    signal_type: str #LONG, SHORT, EXIT
    strength: float = 1.0
    type: EventType = EventType.SIGNAL

@dataclass
class OrderEvent(Event):
    #Generated by Portfolio in response to a signal.
    symbol: str
    order_type: str #MKT, LMT
    quantity: int
    direction: str
    type: EventType = EventType.ORDER

@dataclass
class FillEvent(Event):
    #Generated by ExecutionHandler after an Order is filled
    symbol: str
    datetime: pd.Timestamp
    quantity: int
    direction: str
    fill_price: float
    commission: float
    type: EventType = EventType.FILL

    
    